backend:
  name: git-gateway
  branch: main  # Branch do seu repositório
  base_url: https://doisembarcando.netlify.app/
  auth_endpoint: api/auth/

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "countries"
    label: "Countries"
    folder: "public/content/countries"
    create: true
    slug: "{{fields.name | slugify}}"
    fields:
      - label: "Country Name"
        name: "name"
        widget: "string"
      - label: "Country Description"
        name: "description"
        widget: "text"
      - label: "Language"
        name: "language"
        widget: "string"
      - label: "Currency"
        name: "currency"
        widget: "string"
      - label: "Population"
        name: "population"
        widget: "number"
      - label: "Visa Requirements"
        name: "visa_requirements"
        widget: "text"
      - label: "Traditions and Culture"
        name: "traditions"
        widget: "markdown"
      - label: "Transportation Guide"
        name: "transportation_guide"
        widget: "markdown"
      - label: "Highlights"
        name: "highlights"
        widget: "list"
        fields:
          - label: "Name"
            name: "highlight_name"
            widget: "string"
          - label: "Description"
            name: "highlight_description"
            widget: "text"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Description"
            name: "image_description"
            widget: "string"

  - name: "regions"
    label: "Regions"
    folder: "public/content/regions"
    create: true
    slug: "{{fields.name | slugify}}"
    fields:
      - label: "Region Name"
        name: "name"
        widget: "string"
      - label: "Region Description"
        name: "description"
        widget: "text"
      - label: "Highlights"
        name: "highlights"
        widget: "list"
        fields:
          - label: "Name"
            name: "highlight_name"
            widget: "string"
          - label: "Description"
            name: "highlight_description"
            widget: "text"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Description"
            name: "image_description"
            widget: "string"

  - name: "cities"
    label: "Cities"
    folder: "public/content/cities"
    create: true
    slug: "{{fields.name | slugify}}"
    fields:
      - label: "City Name"
        name: "name"
        widget: "string"
      - label: "City Description"
        name: "description"
        widget: "text"
      - label: "Best Time to Visit"
        name: "best_time"
        widget: "string"
      - label: "Transportation"
        name: "transportation"
        widget: "text"
      - label: "Tourist Rating"
        name: "rating"
        widget: "number"
      - label: "Highlights"
        name: "highlights"
        widget: "list"
        fields:
          - label: "Name"
            name: "highlight_name"
            widget: "string"
          - label: "Description"
            name: "highlight_description"
            widget: "text"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
          - label: "Description"
            name: "image_description"
            widget: "string"

  - name: "blog"
    label: "Blog Posts"
    folder: "public/content/blog"
    create: true
    slug: "{{fields.name | slugify}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: []
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
